Decorate a class
Abdulwhbhussain/OOP-school-library pull request #2
Opened 2023-08-29 19:43 UTC by Abdulwhbhussain

Project requirements
Check the usage of [Decorator pattern in Ruby](https://refactoring.guru/design-patterns/decorator/ruby/example#example-0)
Think about how you can use two decorators in order to capitalize and trim people's names.
In the following steps you will get instructions for implementing the Decorator design pattern for this case.
Interface
Create a class Nameable.
Implement a method called correct_name that will raise a NotImplementedError.
Turn your Person class to Nameable
Make sure that your Person class inherits from Nameable
Make sure that this class has a method correct_name implemented. It should simply return the name attribute.
Prepare base Decorator
Make sure that it inherits from Nameable.
In the constructor assign a nameable object from params to an instance variable.
Implement the correct_name method that returns the result of the correct_name method of the @nameable.
Prepare CapitalizeDecorator and TrimmerDecorator
For the CapitalizeDecorator:
Create a class that inherits from the base Decorator class.
Implement a method correct_name that capitalizes the output of @nameable.correct_name.
For the TrimmerDecorator:
Create a class that inherits from the base Decorator class.
Implement a method correct_name that makes sure that the output of @nameable.correct_name has a maximum of 10 characters. If it's longer it should trim the word.

2023-08-29 21:05 UTC, Felix45 requested changes
Hi @Abdulwhbhussain, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif" width="350px" />

## Highlights :heavy_check_mark: 
- [x] Decorator design pattern is implemented :white_check_mark: 
- [x] Git flow is used correctly :white_check_mark: 
- [x] Pull request has a descriptive title and summary :white_check_mark: 
- [x] Repository has a professional readme file :white_check_mark:   


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-29 21:05 UTC, Felix45 commented on classes/base_decorator.rb
> +require './nameable'
- [ Required ] I think it would be nice if you use the `require_relative` statement to include the `nameable.rb` into the `base_decorator` file. In ruby convention, the `require_relative` statement is usually used to include user-defined files e.g. `nameable.rb` while the `require` statement is usually used to require ruby files e.g `gems`

## Example code
```ruby
require_relative 'nameable'
```

2023-08-29 21:05 UTC, Felix45 commented on classes/person.rb
> +require './nameable'
- [ Required ] I think it would be nice if you use the `require_relative` statement to include the `nameable.rb` into the `base_decorator` file. In ruby convention, the `require_relative` statement is usually used to include user-defined files e.g. `nameable.rb`, `base_decorator.rb`,  while the `require` statement is usually used to require ruby files e.g `gems`

## Example code
```ruby
require_relative 'nameable'
```

2023-08-29 21:05 UTC, Felix45 commented on classes/capitalize_decorator.rb
> +class CapitalizeDecorator < BaseDecorator
- [ Required ] I think it would be nice if you imported the `BaseDecorator` class into this file before using it. If you use the class before requiring it into the file, it will cause an error. Please see the example below as a suggestion on how to achieve this.

## Example code 
```ruby
require_relative 'base_decorator'

class CapitalizeDecorator < BaseDecorator
  def correct_name
    @nameable.correct_name.capitalize
  end
end
```

2023-08-29 21:05 UTC, Felix45 commented on classes/trimmer_decorator.rb
> +class TrimmerDecorator < BaseDecorator
- [ Required ] I think it would be nice if you imported the `BaseDecorator` class into this file before using it. If you use the class before requiring it into the file, it will cause an error. Please see the example below as a suggestion on how to achieve this.

## Example code
```ruby
require_relative 'base_decorator'

class TrimmerDecorator < BaseDecorator
  def correct_name
    return @nameable.correct_name.slice(0, 10) if @nameable.correct_name.size > 10

    @nameable.correct_name
  end
end
```

2023-08-29 21:25 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @Abdulwhbhussain,

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

![giphy (1)](https://user-images.githubusercontent.com/68796232/223283296-e4ee61b3-5609-4707-a1c7-5a3da02d5db9.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-08-30 10:17 UTC, merged

2023-10-02 23:57 UTC, skyv26 reviewed
## Hi @Abdulwhbhussain, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNWRlMTU1MTgyOWI3OTNiMGUxOWQ3NTUxNDc4YWE5MTY0YWFmNmEwYyZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/Ti0pkgccBnF7Xy1vhk/giphy-downsized-large.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Professional `README` template ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._